workflows:
  ci:
    name: CI
    instance_type: mac_mini
    # Setting the timeout for a build to 15 minutes.
    max_build_duration: 15
    environment:
      # Using the latest Flutter version.
      flutter: stable
    # This workflow should trigger when a new pull request opens or updates.
    triggering:
      events:
        - pull_request
    scripts:
      - name: Melos Bootstrap
        script: |
          # Add Dart to PATH
          echo 'export PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin"' >>~/.bashrc 
          echo 'export PATH="$PATH":"$FLUTTER_ROOT/bin"' >>~/.bashrc 
          source ~/.bashrc

          dart pub global activate melos
          melos bootstrap

      - name: Run Tests
        script: |
          # Add Dart to PATH
          echo 'export PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin"' >>~/.bashrc 
          source ~/.bashrc

          $FLUTTER_ROOT/.pub-cache/bin/melos run test

      - name: Run Format
        script: |
          # Add Dart to PATH
          echo 'export PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin"' >>~/.bashrc 
          source ~/.bashrc

          melos run format

      - name: Run Tests
        script: |
          # Add Dart to PATH
          echo 'export PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin"' >>~/.bashrc 
          source ~/.bashrc

          melos run test
